### ISSUE TITLE
Using urbandictionary api instead of scraping

### ISSUE THREAD

**Issue by albacoretuna** [prdpx7/webdict#1]
Hi and thanks for this useful tool :) 

I found this api that can be used for urbandictionary, might be better than scraping, I don't know:
api.urbandictionary.com/v0/define?term=IIRC

**Comment by prdpx7** [comment]
thanks..
but i'm scraping dictionary.com and using api for urbandictionary.
https://github.com/zuck007/webdict/blob/master/index.js#L5
