### ISSUE TITLE
 "404 Not Found" -> webdict 'urbandictionary' won't return definitions

### ISSUE THREAD

**Issue by mattdellomo** [prdpx7/webdict#3]
webdict was working then, at around 10pm EST on July 19th it stopped sending/returning definitions.

Looks like  there was a update on a server and a resource got moved, deleted, or changed. 
**"404 Not Found"**

Here is my code:

const webdict = require('webdict');

var x = 'hello';

webdict('urbandictionary', x)
  .then(response => {
    console.log(response);
});

Here is my Output:

{ statusCode: 404,
  message: 'check the spelling again',
  source: 'http://urbandictionary.com' }

Thanks,

**Comment by Votyn** [comment]
Can confirm this is still an issue. Screenshot from runkit:
![image](https://user-images.githubusercontent.com/23479402/43081486-e9208988-8e89-11e8-80b4-97be5558c74a.png)

**Comment by prdpx7** [comment]
fixed it!

**Comment by mattdellomo** [comment]
confirmed working!

Thanks,
